### ISSUE TITLE
`[[tool.poetry.packages]]` sections can cause the lock package to fail to build

### ISSUE THREAD

**Issue by fish-face** [bneijt/poetry-lock-package#20]
E.g. include the following snippet:

```toml
[[tool.poetry.packages]]
include = "package"
from = "src"
```

Will complain because `src/package` does not exist in the lock package directory.
